package raf.draft.dsw.controller.observer;

public enum EventTypes {
    MESSAGE_GENERATED, NODE_DOUBLE_CLICK,
    NODE_CREATED, NODE_DELETED, NODE_EDITED, CHILD_ADDED, CHILD_REMOVED,
    ROOM_DIMENSIONS_CHANGED, VISUAL_ELEMENT_EDITED,
    NODE_SAVED_CHANGED;
}
