package raf.draft.dsw.controller.observer;

public enum EventTypes {
    MESSAGE_GENERATED, NODE_DOUBLE_CLICK, NODE_CREATED, NODE_DELETED, NODE_EDITED, VISUAL_ELEMENT_CREATED, VISUAL_ELEMENT_DELETED, VISUAL_ELEMENT_EDITED;
}
